version: 0.2

phases:
  pre_build:
    commands:
       - echo login into ECR
       - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 486127124488.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t reviews:comprehend .
      - docker tag reviews:comprehend 486127124488.dkr.ecr.ap-southeast-1.amazonaws.com/reviews:comprehend
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 486127124488.dkr.ecr.ap-southeast-1.amazonaws.com/reviews:comprehend